name: Generate GitHub Pulse

on:
  schedule:
    - cron: "15 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write   # allow git push
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # use GITHUB_TOKEN for push
          fetch-depth: 0

      - name: Generate main metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 49ochieng
          template: classic
          base: header, activity, repositories
          config_timezone: Africa/Nairobi
          repositories: 200
          repositories_forks: yes
          commits_authoring: 49ochieng, 49ochieng@users.noreply.github.com
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          filename: metrics.svg

      - name: Verify file exists
        run: |
          ls -la
          test -f metrics.svg || (echo "metrics.svg not generated" && exit 1)

      - name: Commit SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          git commit -m "chore: update metrics" || echo "No changes to commit"
          git push
